[package]
authors = ["The wasm-bindgen Developers"]
description = "Internal testing macro for wasm-bindgen"
edition = "2021"
include = ["/LICENSE-*", "/src"]
license = "MIT OR Apache-2.0"
name = "wasm-bindgen-test-macro"
repository = "https://github.com/wasm-bindgen/wasm-bindgen"
rust-version = "1.71"
version = "0.3.58"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", default-features = false, features = [
  "parsing",
  "proc-macro",
  "derive",
  "printing",
] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
trybuild = "1.0"
wasm-bindgen-test = { path = "../test" }

[lints]
workspace = true
