[package]
name = "codspeed-napi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.100"
codspeed = "4.1.0"
napi = "3"
napi-derive = "3"
serde_json = "1.0.145"

[build-dependencies]
napi-build = "1"
